# Generated by Django 3.1.7 on 2021-05-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('extra_help', models.TextField(blank=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('save_answers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LawCaseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipient', models.TextField(blank=True)),
                ('sender', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('signature', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, max_length=50)),
                ('success_message', models.TextField()),
                ('failure_message', models.TextField()),
                ('unsure_message', models.TextField()),
                ('order', models.IntegerField()),
                ('law_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_advice_builder.lawcase')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('short_title', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('field_type', models.CharField(choices=[('TX', 'Long multiline Text input'), ('SO', 'Pick one of multiple options'), ('MO', 'Pick several of multiple options'), ('SL', 'Short single line text input'), ('FU', 'File Upload'), ('DT', 'Date')], default='SO', max_length=2)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('parent_option', models.CharField(blank=True, max_length=200)),
                ('failure_conditions', models.JSONField(blank=True, default=list, null=True)),
                ('success_conditions', models.JSONField(blank=True, default=list, null=True)),
                ('unsure_options', models.JSONField(blank=True, default=list, null=True)),
                ('information', models.TextField(blank=True)),
                ('success_message', models.TextField(blank=True)),
                ('failure_message', models.TextField(blank=True)),
                ('unsure_message', models.TextField(blank=True)),
                ('questionaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal_advice_builder.questionaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lawcase',
            name='law_case_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.lawcasetemplate'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict, null=True)),
                ('message', models.TextField(blank=True)),
                ('rendered_document', models.TextField(blank=True, verbose_name='Rendered Document')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('law_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_advice_builder.lawcase')),
            ],
        ),
    ]
