# Generated by Django 3.1.7 on 2021-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rendered_document',
            field=models.TextField(blank=True),
        ),
    ]
