# Generated by Django 3.2.8 on 2021-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0002_alter_question_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
