# Generated by Django 3.1.7 on 2021-06-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0002_auto_20210531_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sample_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sender',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documentfieldtype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='lawcase',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.document'),
        ),
    ]
