# Generated by Django 3.1.7 on 2021-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0002_answer_rendered_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawcase',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
    ]
