# Generated by Django 3.2.8 on 2021-10-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0003_answer_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('TX', 'Long multiline Text input'), ('SO', 'Pick one of multiple options'), ('MO', 'Pick multiple of multiple options'), ('SL', 'Short single line text input'), ('DT', 'Date'), ('YN', 'Yes/No')], default='SO', max_length=2),
        ),
    ]
