# Generated by Django 3.1.7 on 2021-05-06 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0004_lawcasetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawcase',
            name='law_case_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.lawcasetemplate'),
        ),
    ]
