# Generated by Django 3.1.7 on 2021-07-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0004_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('TX', 'Long multiline Text input'), ('SO', 'Pick one of multiple options'), ('MO', 'Pick several of multiple options'), ('SL', 'Short single line text input'), ('FU', 'File Upload'), ('DT', 'Date'), ('YN', 'Yes/No')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='success_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='unsure_message',
            field=models.TextField(blank=True),
        ),
    ]
