# Generated by Django 3.2.8 on 2021-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0005_auto_20211028_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawcase',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
