# Generated by Django 3.1.7 on 2021-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0005_auto_20210709_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawcase',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lawcase',
            name='save_answers',
            field=models.BooleanField(default=True),
        ),
    ]
