# Generated by Django 3.1.7 on 2021-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0006_auto_20210507_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='failure_conditions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
