# Generated by Django 3.1.7 on 2021-05-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0007_question_failure_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='failure_conditions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
