# Generated by Django 3.1.7 on 2021-07-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0010_auto_20210719_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='then_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.question'),
        ),
    ]
