# Generated by Django 3.1.7 on 2021-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0011_auto_20210516_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawcase',
            name='result_template',
        ),
        migrations.RemoveField(
            model_name='question',
            name='failure_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='success_options',
        ),
        migrations.AlterField(
            model_name='answer',
            name='rendered_document',
            field=models.TextField(blank=True, verbose_name='Rendered Document'),
        ),
    ]
