# Generated by Django 3.1.7 on 2021-08-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0012_auto_20210730_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.documenttype'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='field_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.documentfieldtype'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='success_message',
            field=models.TextField(blank=True, help_text='This message is shown if the user has reached the end of this questionaire successfully.'),
        ),
    ]
