# Generated by Django 3.1.7 on 2021-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0012_auto_20210517_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawcase',
            name='extra_help',
            field=models.TextField(blank=True),
        ),
    ]
