# Generated by Django 3.1.7 on 2021-08-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0013_auto_20210805_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LawCaseTemplate',
        ),
    ]
