# Generated by Django 3.1.7 on 2021-08-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0014_delete_lawcasetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_text_blocks', to='legal_advice_builder.document')),
                ('document_fields', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_text_blocks', to='legal_advice_builder.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
