# Generated by Django 3.1.7 on 2021-08-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0017_textblock_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='documentfieldtype',
            name='document_type',
        ),
    ]
