# Generated by Django 3.1.7 on 2021-08-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0019_remove_textblock_document_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='document',
        ),
        migrations.DeleteModel(
            name='DocumentFieldType',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='DocumentField',
        ),
    ]
