# Generated by Django 3.1.7 on 2021-08-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0022_auto_20210813_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_advice_builder.question'),
        ),
    ]
