# Generated by Django 3.1.7 on 2021-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_advice_builder', '0023_auto_20210817_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('TX', 'Long multiline Text input'), ('SO', 'Pick one of multiple options'), ('SL', 'Short single line text input'), ('DT', 'Date'), ('YN', 'Yes/No')], default='SO', max_length=2),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='success_message',
            field=models.TextField(blank=True, default='your message here ...', help_text='This message is shown if the user has answered all questions successfully.'),
        ),
    ]
