# Generated by Django 3.1.7 on 2021-08-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal_advice_builder', '0024_auto_20210818_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawcase',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
